"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const CompanyAccount_1 = require("./class/CompanyAccount");
const PeopleAccount_1 = require("./class/PeopleAccount");
const peopleAccount = new PeopleAccount_1.PeopleAccount(1, 'Nath', 10);
console.log(peopleAccount);
peopleAccount.deposit();
const companyAccount = new CompanyAccount_1.CompanyAccount('DIO', 20);
companyAccount.deposit();
console.log(companyAccount);
